config/routes.rb
Blog::Application.routes.draw do
  get "admin/index"
  get "admin/destroy"
  get "admin/show"

  resources :articles do
    member do
    post :notify_friend
    end

  resources :comments
  
  end

  resources :users
  resources :profiles
  resource :session
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

  root :to => "articles#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
belongs_to :user

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def index
		@profile=current_user.profile
	end
	def new
		@profile=Profile.new
	end
	def create
		@profile=Profile.new(params[:profile])
		@user=current_user
		@user.profile=@profile
		@profile.user_id=current_user.id
		if @profile.save
			redirect_to profiles_path
			else
				render :new
			end
			end
			def edit
				@profile=Profile.find(params[:id])
			end
			def show
				@profile=Profile.find(params[:id])
			end
		def update
		@profile=Profile.find(params[:id])
		if @profile.update_attributes(params[:profile])
			redirect_to profiles_path
			else
				render :edit
			end
			end
			def destroy
				@profile=Profile.find(params[:id])
				@profile.destroy
				redirect_to profiles_path
				end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<%=form_for @profile do |pro| %>
<div class="field">
<%= pro.label :Name %>
<%= pro.text_field :name%>
</div>
<div class="field">
<%= pro.label :Age %><br />
<%= pro.text_field :age%>
</div>
<div class="field">
<%= pro.label :worked_at %><br />
<%= pro.text_field :worked_at%>
</div>
<div class="field">
<%= pro.label :Designation %><br />
<%= pro.text_field :designation%>
</div>
<div class="field">
<%= pro.label :City %><br />
<%= pro.text_field :city%>
</div>
<div class="action">
<%= pro.submit "Update"%>
</div>
<%end%>
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Profile</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Worked At</th>
    <th>Designation</th>
    <th>City</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>


  <tr>
    <td><%=  @profile.name %></td>
    <td><%=  @profile.age %></td>
    <td><%= @profile.worked_at %></td>
    <td><%=  @profile.designation%></td>
    <td><%=  @profile.city %></td>
    <td><%= link_to 'Show', @profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(@profile) %></td>
    <td><%= link_to 'Destroy', @profile, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>

</table>

<br />

<%= link_to 'Back', '/articles' %>

app/views/profiles/new.html.erb
<%=form_for @profile do |pro| %>
<div class="field">
<%= pro.label :Name %>
<%= pro.text_field :name%>
</div>
<div class="field">
<%= pro.label :Age %><br />
<%= pro.text_field :age%>
</div>
<div class="field">
<%= pro.label :worked_at %><br />
<%= pro.text_field :worked_at%>
</div>
<div class="field">
<%= pro.label :Designation %><br />
<%= pro.text_field :designation%>
</div>
<div class="field">
<%= pro.label :City %><br />
<%= pro.text_field :city%>
</div>
<div class="action">
<%= pro.submit "Create"%>
</div>

<%end%>
<%= link_to 'Back', articles_path %>

app/views/profiles/show.html.erb
Name: <%=  @profile.name %><br/>
	Age: <%=  @profile.age %><br/>
	Worked_at: <%= @profile.worked_at %><br/>
	Designation: <%=  @profile.designation%><br/>
	City: <%=  @profile.city %><br/>
	<%= link_to 'Back', profiles_path %>